### ISSUE TITLE
How to end snippets?

### ISSUE THREAD

**Issue by Sidneys1** [draivin/hsnips#1]
The following snippet replaces the text you type with a lowercase version with spaces replaced with `-`. However, pressing tab doesn't seem to "end" the snippet - subsequent typing still gets `.toLowerCase()` and `.replace(/ /g, '-')` applied.

```
snippet slug "Markdown Slug"
$0``rv = t[0].toLowerCase().replace(/ /g, '-')``
endsnippet
```

I feel like pressing tab should always end the snippet capture if the last input (`$0`) is selected.

**Comment by Sidneys1** [comment]
Also, I feel like the actual snippet above shouldn't work...

Typing `slug\tTest Text` should output `Test Texttest-text`, but instead only outputs `test-text`.

**Comment by draivin** [comment]
Hey, so the snippet is set to end when it "loses focus", as in your selection goes outside the area of the snippet.

I agree there should be some way to end it when the `$0` tabstop is inside the snippet, but I'm not really sure `tab` is the way to go, at least I wouldn't naturally expect pressing `tab` to not insert anything and instead finish the snippet. I probably could implement it, but if you have any other suggestions you feel are more natural please send them my way!

And you're right, the above shouldn't work, it's an issue I'm actually aware about, when you have a tabstop right next to a code block it will "eat" the content of the tabstop, I'm still thinking about the best way to fix it! I'll come back to it as soon as I'm a little less busy.

**Comment by Sidneys1** [comment]
Hmm. Ok, so would the proper way to write this snippet be:

```
snippet slug "Markdown Slug"
$1 ``rv = t[0].toLowerCase().replace(/ /g, '-')`` $0
endsnippet
```

The space between `$1` and ` `` ` should fix the "gobbling", and the use of `$1` and then `$0` at the end should mean I can tab to `$0` to end the snippet..?

**Comment by draivin** [comment]
That would work avoid the issues, you could even not write the `$0` at the end and let vscode auto insert it for you, but the original code should work as well, even though right now it doesn't.

**Comment by draivin** [comment]
Fixed the above issues, you can now leave the active snippet by pressing the escape key!
