### ISSUE TITLE
Is there a way to get rid of the marked spaces?

### ISSUE THREAD

**Issue by TheGrowingPlant443** [draivin/hsnips#106]
My code is:
```
snippet if "if" Ai
if$1 

end$0
endsnippet
```
When I write ```if``` it does as it suppose to expect when i hit space again afterwards it has marked the area I am in after the ```if``` statement I would like to not have that light mark. (End statement is invisible).

![image](https://user-images.githubusercontent.com/57142309/148645496-58a036c4-0510-48b8-8e8f-e2bfb2e5b638.png)

**Comment by TheGrowingPlant443** [comment]
I found out

**Comment by gruvw** [comment]
What was the issue ? I could not reproduce.

**Comment by TheGrowingPlant443** [comment]
The solution was to use this code

```
snippet if "if" A
if$0

end
endsnippet
```
Then it stopped making the bright spaces.
