### ISSUE TITLE
Hyper Snips not recognizing text environment with mathmode in LaTeX

### ISSUE THREAD

**Issue by vikomen** [draivin/hsnips#107]
Whenever I have \text{} within a math environment, be it $ $ or $$ $$ or align, when I write text inside the percentages, code is still executed as if I was still in math mode. Moreover, in the Runtime Status, I get that the scrope/environment "text" is not recognized. Has anyone been able to fix this?

**Comment by gruvw** [comment]
I did it that way in my [latex-setup](https://github.com/gruvw/latex-setup):
```
global
function math(context) {
    return context.scopes.some(s => s.startsWith("meta.math")) && !context.scopes.some(s => s.startsWith("comment") || s.startsWith("meta.text.normal.tex"));
}
endglobal
```
Does this solve you problem ?

**Comment by vikomen** [comment]
Hi, it seems to still not work. I still get these errors 
![image](https://user-images.githubusercontent.com/91122493/150959698-61c597fc-af33-42a7-8956-a703267a2786.png)

**Comment by gruvw** [comment]
I don't have the same issues, can you try to launch a new environment only with the snippet I provided to see if this is coming from one of your other snippets ?

**Comment by draivin** [comment]
Hi @vikomen, does this issue still affects you? If so, could you please reopen the issue? Thanks.
