### ISSUE TITLE
THE CODE DOESN'T WORK ANYMORE!!!!

### ISSUE THREAD

**Issue by franto666** [draivin/hsnips#109]
Hi everyone,
I have a problem with Hypersnips: Up to now all my snippets that were implemented with the code went, but now, I have no idea why, no one goes anymore, as if an update no longer recognizes the Javascript code implementation .

Here there is an example of snippet:

snippet `p([a-zA-Z]+)-` "prods_with_indices" A
``
//Sijk- => \sum_{i=0}^{+\infty}\sum_{j=0}^{+\infty}\sum_{k=0}^{+\infty}
//Saabb- => \sum_{\alpha=0}^{+\infty}\sum_{\beta=0}^{+\infty}
transliteration = {"a": "\\alpha", "b": "\\beta", "g": "\\gamma", "G": "\\Gamma", "d": "\\delta", "D": "\\Delta", "e": "\\epsilon", "E": "\\varepsilon", "z": "\\zeta", "h": "\\eta", "t": "\\theta", "T": "\\Theta", "k": "\\kappa", "i": "\\iota", "l": "\\lambda", "L": "\\Lambda", "m": "\\mu", "n": "\\nu", "x": "\\xi", "X": "\\Xi", "p": "\\pi", "P": "\\Pi", "r": "\\rho", "s": "\\sigma", "S": "\\Sigma", "o": "\\omega", "O": "\\Omega", "c": "\\chi", "f": "\\phi", "F": "\\Phi", "y": "\\upsilon", "Y": "\\Upsilon", "v": "\\psi", "V": "\\Psi", "u": "\\tau" };

let index = "a"; //current index for sum
for (i=0; i < m[1].length; i++) {
    if ((i < m[1].length - 1) && (m[1][i] == m[1][i+1])) { //greek letters
        //rv += "got double " + m[1][i] + "\n";
        i += 1; //skip repeated character
        index = transliteration[m[1][i]] || (m[1][i] + m[1][i]);
    }
    else {
        index = m[1][i];
    }

    rv += '\\prod_{' + index + '=${' + (2*i+1) + ':0}}^{${' + (2*i+2) + ':+\\infty}} \\ ';
}
``
endsnippet

**Comment by gruvw** [comment]
Please take a look at https://github.com/draivin/hsnips/issues/97#issuecomment-997126076

**Comment by draivin** [comment]
We should probably address this on the readme, but as stated, this is a syntax change, thanks for the issue report.
