### ISSUE TITLE
Flags i

### ISSUE THREAD

**Issue by lancerXXXX** [draivin/hsnips#11]
In the Ultisnips for vim, there are flags 'A' and 'i'
this extension have flag A
but I think 'i' is also a useful flag
such as using latex in markdown
$if I use snips here$
the snips won't trigger,because it is next to '$'
I have to print  space twice
$  $
then back to the middle, to print

**Comment by draivin** [comment]
I've thought about adding the `i` flag, but as I see it, the regexp mode is actually more powerful, and as it stands currently if I'm not mistaken, it is able to trigger in the middle of a word.

If you can't get it to work or if there is another use case where the regexp is not a useful replacement please let me know! For now I'm closing this issue.

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/72675188-95846a80-3abb-11ea-8779-232a99db4e57.png)
![image](https://user-images.githubusercontent.com/42160297/72675191-a2a15980-3abb-11ea-9393-4c72c5841e1e.png)
First I use the first snip `gongshi`
![image](https://user-images.githubusercontent.com/42160297/72675214-e72cf500-3abb-11ea-97a1-c6982c46b273.png)
then I use the second snip `fenshu`
![image](https://user-images.githubusercontent.com/42160297/72675293-4f7bd680-3abc-11ea-9e14-f832270acb23.png)
But the prompt does not appear
so I change the first snip
![image](https://user-images.githubusercontent.com/42160297/72675299-733f1c80-3abc-11ea-9aa6-d25a4ee44e51.png)
then
![image](https://user-images.githubusercontent.com/42160297/72675303-80f4a200-3abc-11ea-954b-89c89b3c9958.png)
![image](https://user-images.githubusercontent.com/42160297/72675322-c44f1080-3abc-11ea-966e-338316017a1b.png)

But the math doesn't render if there's a space next to the $

Then I need to move the cursor to remove the Spaces

For example, if I use latex to take notes in class, I can't keep up with him

![image](https://user-images.githubusercontent.com/42160297/72675372-b221a200-3abd-11ea-9cd8-e8f737987cee.png)

but
![image](https://user-images.githubusercontent.com/42160297/72675377-bf3e9100-3abd-11ea-8e6a-964e3b92320b.png)

the `gongshi` doesn't trigger

Vscode can almost replace vim
Ultisnips is the only one that still keeps me on vim to take notes on class
on all accounts, I was pleasantly surprised by your extension

**Comment by draivin** [comment]
Try using the following snippet instead:

```
snippet `fenshu` "name" A
```

When you surround the trigger text with backticks it activates regexp mode, which is more tolerant with those kinds of things.

**Comment by lancerXXXX** [comment]
I've learned
Thank you
