### ISSUE TITLE
WSL

### ISSUE THREAD

**Issue by kingdellaprogrammazione** [draivin/hsnips#114]
Hello, I'm using WSL 2 , where do I have to put the .hsnips file to make the extension work?

**Comment by draivin** [comment]
Sorry for the delay, the default path in which the extension looks for the snippets files is 

    Windows: %APPDATA%\Code\User\hsnips\(language).hsnips
    Mac: $HOME/Library/Application Support/Code/User/hsnips/(language).hsnips
    Linux: $HOME/.config/Code/User/hsnips/(language).hsnips

As WSL2 is a linux instance, I imagine the latter one is the correct path. Alternatively, you can change the setting `hsnips.hsnipsPath` and set a custom path for the snippets.
