### ISSUE TITLE
Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by Mrxixixixi** [draivin/hsnips#116]
When I type, there is no hint appearing.So I check the runtime status of HyperSnips, there seems to be something wrong. 
![image](https://user-images.githubusercontent.com/36095714/161419564-98a22f90-6c30-4bb1-b44f-5305a9be758d.png)

**Comment by yfzhao20** [comment]
Can you provide your snippets? Try to disable some snippets, and test again.

See https://github.com/draivin/hsnips/issues/112.

**Comment by draivin** [comment]
This should be fixed as of latest version, please reopen the issue if it happens again.
