### ISSUE TITLE
Seems to conflict with json-language features

### ISSUE THREAD

**Issue by dlgombert** [draivin/hsnips#121]
Can't say definitively because the log says a bunch of stuff that is too hard to trace.   However, when I installed this extension, saving json files would hang and a popup would say waiting for json language features.  Tried various things to no avail.  Disabling this extension fixed it instantly.

**Comment by gruvw** [comment]
Oh yes for sure, opening settings.json (user scope) takes 30 seconds before I can type anything.
I don't know if it conflicts with vim/json but there's something fishy going on here.

**Comment by Msadat97** [comment]
I noticed this as well. The reason according to VSCODE logs is the HyperScope extension that becomes unresponsive when opening settings.json. It would be great to have a fix for this.

**Comment by LogicNg** [comment]
same problem here

**Comment by draivin** [comment]
Should be fixed as of latest version.
