### ISSUE TITLE
context snippet malfunctions

### ISSUE THREAD

**Issue by jasonyux** [draivin/hsnips#122]
I have been using this extension for quite a long time (works beautifully), until recently the following context function no longer works as expected:
```
global
function math(context) {
    return context.scopes.some(s => s.startsWith("meta.math"));
}
endglobal

// some snippets omitted
context math(context)
snippet hat "hat" wA
\hat{$1}$0
endsnippet
```

such that when typing in a `.tex` file, even when I checked using `Developer: Inspect Editor Tokens and Scopes ` that I am at a `textmate scopes | text.tex.latex` block, i.e. just **typing some normal text, typing `hat` still managed to expand**. 

I wonder what could have gone wrong/how I can debug the issue?

**Comment by jasonyux** [comment]
#79 Seems to have the same issue. In my case this glitch is not random but happens all the time

**Comment by jasonyux** [comment]
I tried downgrading to `v0.2.7` and it **seems to work** for now. In this case it seems that there is a bug with `v0.2.8`? Is someone else also encountering this issue with `v0.2.8`?

**Comment by DedZago** [comment]
I am encountering this issue too in markdown, especially when inserting different mathematical environments from a snippet that contains a `$0` tabstop.

In those cases, I have found that temporary workarounds are: 

* Switching the cursor to the inserted environment a couple of times lets the scope function correctly again sometimes.
* Restarting the window with `Developer: Reload window` always resets the scope correctly.

**Comment by hinell** [comment]
We need a better mechanis for contxt matching really.

**Comment by draivin** [comment]
Should be greatly improved as of latest patch, if there are new issues please open a new issue or reopen this one.
