### ISSUE TITLE
Brackets aren't properly read

### ISSUE THREAD

**Issue by Alex2134556** [draivin/hsnips#125]
I am having an issue with a simple snippet function. I have the following snippet (the actual snippet is a bit longer, this is to produce a simple test example)
```
context math(context)
snippet `^.*\};` A
``
rv =  m[0];
``
```
Then using this with the trigger `;` on 
`\[ \{a+b\} \]`
produces the output 
`\[ \{a+b} \]`
even though the expected output should be identical. 

Can this please be fixed?

**Comment by draivin** [comment]
This is not so much an issue as an escaping problem, it interprets the slashes coming from `m[0]` as escape characters, if you want a literal slash a simple workaround is to use the following snippet:
```lua
snippet `^.*\};` A
``
rv =  m[0].replace(/\\/g,'\\\\');
``
endsnippet
```
