### ISSUE TITLE
Dynamically generated tabstops

### ISSUE THREAD

**Issue by runxuanjiang** [draivin/hsnips#130]
Hi,

I was wondering if there is some functionality in hsnips that will allow us to create dynamically generated tabstops, as seen in ultisnips:
https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/README.md

Thanks!

**Comment by gruvw** [comment]
Yes there is, using `snip.tabstop(1)` with JS interpolation.

You can see some examples in my LaTeX config here: https://github.com/gruvw/latex-setup/blob/d35eb31c98c2c717c8e33f0ef2f05f91b515b7d5/latex.hsnips#L404

**Comment by runxuanjiang** [comment]
Awesome, thanks!

**Comment by hinell** [comment]
@gruvw This needs to be documented.

**Comment by gruvw** [comment]
Yes, I argree.

We could have an example explaining this syntax/feature in the readme.  
#97 (https://github.com/draivin/hsnips/issues/97#issuecomment-997126076) is the initial issue that introduced this feature.
