### ISSUE TITLE
Tab stops not working in nested snippets

### ISSUE THREAD

**Issue by danirui** [draivin/hsnips#135]
I describe the issue in detail in this link: https://stackoverflow.com/questions/74251138/vscode-snippets-hypersnips-tab-stops-in-nested-use-of-snippets

**Comment by gruvw** [comment]
Hi, do you have the Vim extension installed in VSCode ?  
If so, does the problem still occurs when you disable the Vim extension ?

(see #78)

**Comment by danirui** [comment]
Following #126, using VSCode neovim seems to work fix this issue (using `homebrew` as discussed in https://github.com/neovim/neovim/wiki/Installing-Neovim, and following this video https://www.youtube.com/watch?v=ZEFXeRIFvN0&ab_channel=LinuxBTW to edit `init.vim` as necessary).
