### ISSUE TITLE
Context definition does not work with rmd.hsnips or rmarkdown.hsnips files

### ISSUE THREAD

**Issue by baikaltaiga** [draivin/hsnips#144]
I tried to use the hsnips extension for rmarkdown. The extension works well with markdown files and latex files, but for some reason I cannot get it to work properly with rmarkdown. Specifically, for snippets defined in math context, such as:

Context definition: 

``` java
     function math(context) {
            return context.scopes.some(s => s.includes("math"));
        }

    // inline & block math

        function inline_math(context){
            return context.scopes.some(s => s.includes("math.inline"));
        }

        function block_math(context){
            return context.scopes.some(s => s.includes("math.block")) || context.scopes.some(s => s.includes("math.display"));
        }
```

Example snippets:

```
context math(context)
snippet `(;;;|cdot)` "cdots" iA
``rv='\\cdots'``
endsnippet

context math(context)
snippet `par` "partial" iA
``rv="\\partial "``
endsnippet
```

These snippets do not activate. But snippets defined without the context activate properly, such as:

```
snippet `\\dm` "display math" bA
$$
$1
$$
$0
endsnippet
```

I cannot figure out why. I tried to store the snippets in a rmd.hsnips, Rmd.hsnips, rmarkdown.hsnips, and Rmarkdown.hsnips in the designated directory, but the above issue persists. 

After researching on this, I figured out that the vscode textmate scopes in the `$$ $$` is not properly defined. The math scope is missing (see below screen shot):

![image](https://user-images.githubusercontent.com/94728762/211220174-447a8d4b-152e-4157-980e-a8d6082d9e95.png)

**Comment by draivin** [comment]
As you pointed out, this seems to be an issue with the language definition, not with hsnips. As such I'll be closing this, since there is nothing I can do on my side. If you think the math scopes should be available in those languages, you should probably contact the maintainers of the language definition files.
