### ISSUE TITLE
Regular expression cannot match line break

### ISSUE THREAD

**Issue by lancerXXXX** [draivin/hsnips#15]
![image](https://user-images.githubusercontent.com/42160297/83347151-89f05c80-a355-11ea-9ed3-4ba5fb8d0652.png)

I want to match `a\nb\nc\n\d.change`

![image](https://user-images.githubusercontent.com/42160297/83347162-a096b380-a355-11ea-9451-db5e57570dc6.png)

I tried these two kinds of measure `(.|\n)` and `[\s\S]`.
but both of them doesn't work

![image](https://user-images.githubusercontent.com/42160297/83347199-e5bae580-a355-11ea-8ccd-32686aa36785.png)

it can only match when they are written in one line

**Comment by draivin** [comment]
Currently the regex matches are performed on a line by line basis so that performance is not degraded as much. I will try to add a tag to the snippets so that it uses multiple lines as context and will get back to you.

**Comment by lancerXXXX** [comment]
Thank you @draivin

**Comment by draivin** [comment]
How many lines do you expect to wrap around with the completions? I'm reluctant to implement this for arbitrarily long contexts, so I need to have some idea of how many lines would be a reasonable amount.

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/83609768-4bef7480-a5b1-11ea-8623-8af88e97d467.png)

I found this problem when I wanna write a snippet to convert the form above to the form below

so how many lines depend on the content I wanna write

on the other hand, can this problem be solved like this 
maybe work with the extension vim

![image](https://user-images.githubusercontent.com/42160297/83611018-eef4be00-a5b2-11ea-802a-a2e4c03e219a.png)

I choose these lines in the visual model (or just from the clipboard if it's no possible to work with another extension ) than I get I an array just like m and t

**Comment by draivin** [comment]
I've just published an update to the extension with an experimental `M` flag for multiline contexts, currently it is limited to at most 20 lines above, could you try it and let me know how it goes?

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/83941503-80b43380-a81e-11ea-9a14-dbb18c3c60de.png)
![image](https://user-images.githubusercontent.com/42160297/83941508-8742ab00-a81e-11ea-993a-13ee1baa6fc2.png)
I tried to write a snippet to change the unordered list to Ordered list, and it goes well

**Comment by draivin** [comment]
Just added option `hsnips.multiLineContext` in last update to configure how many lines should be available to multi line regexes, so this issue should be resolved.
