### ISSUE TITLE
有时无法触发

### ISSUE THREAD

**Issue by long-zm123** [draivin/hsnips#169]
我昨天安装时还可以非常完美的使用，但是今天不可以使用了，我也不知道是什么情况。
本人电脑安装了Pyghon3.0
首先感谢作者的大力开发，谢谢！
求大神的指导帮助，万分感谢！！！

**Comment by long-zm123** [comment]
本人使用VS Code 安装的 Hyperxnips for math 插件。

**Comment by wzh4464** [comment]
It's not the correct extension you mentioned. Request to close this issue.
