### ISSUE TITLE
Everything stop working

### ISSUE THREAD

**Issue by sleepymalc** [draivin/hsnips#183]
The newest version (0.2.9) make everything stop working. Specifically, at least one bug is now the command is not working normally:
<img width="256" alt="image" src="https://github.com/draivin/hsnips/assets/60427058/e562f6ce-054c-43ba-a8a1-da98715387f8">

@draivin This should be addressed ASAP

**Comment by noisnemid** [comment]
rollback to 0.2.7 or 0.2.8, move .hsnips files to the old directory and delete the globalstorage..../hsnips directory.

there 's something buggy in the new version i think, or my usage i wrote some js codes in the hsnips but it suddenly not working.

there might be some change to it's mechanisms, so i have to roll back to an older version.

if you are new to the 0.2.9, and you didn't want to use old versions, plz delete the old config directory which is C:\Users\XXXXXXXX\AppData\Roaming\Code\User\hsnips, for it confused the extension i think.

**Comment by sleepymalc** [comment]
I solve the issue by manually relocate `.hsnips` files into the correct directory.

**Comment by tomasrei** [comment]
> I solve the issue by manually relocate `.hsnips` files into the correct directory.

What do you mean by the correct directory? There is a hsnips.hsnipsPath in settings that point to a folder that contains my .hsnips file. Is that what you mean? 


My settings looks like this:
```
"hsnips.hsnipsPath": "C:\\OneDrive\\Dokument\\_universitetet",
```

where I have a file ```latex.hsnips```. Any ideas on what todo?
