### ISSUE TITLE
Restricting snippets to contexts

### ISSUE THREAD

**Issue by medwatt** [draivin/hsnips#19]
I'm just wondering if it is possible to make some snippets expand only inside certain contexts. For example, if I type "ahat" inside an equation block or inside $ $, I want it to become \hat{a} but if I type "that" anywhere outside an equation block, I don't want it to become \hat{t} but stay as it is. Is something like this possible?

Here's a page where someone does something like this, but in vim: https://castel.dev/post/lecture-notes-1/#context

**Comment by draivin** [comment]
Unfortunately it is blocked on a vscode issue, you can see some thoughts I had about this over here: https://github.com/draivin/hsnips/issues/6.

**Comment by universemaster** [comment]
I have exactly the same use-case as @medwatt - implementing @gillescastel 's snippets in vscode.

Other extensions still use scopes via [vscode-textmate](https://github.com/microsoft/vscode-textmate) see example here: [restore-scope](https://github.com/siegebell/vsc-prettify-symbols-mode/commit/59068712fe05ed5d29d041e907ec6f204067dbce).

Can we not use the vscode-textmate module in this extension?  Particularly interested in math scopes inside markdown.
