### ISSUE TITLE
Consistency in using \

### ISSUE THREAD

**Issue by medwatt** [draivin/hsnips#21]
There seems to some inconsistency in the use of \\.

For example, consider the code below:
```
snippet floor "floor" iA
\left\lfloor $1 \right\rfloor$0
endsnippet
```

Triggering the snippet only prints the first \\.

So, I changed every single \\ into \\\\. Triggering the snippet returns the first \\ as \\\\ while the other ones as \\.

It seems to get the expected result, one needs to write things as shown below. While this is a trivial issue, it seems inconsistent.

```
snippet floor "floor" iA
\left\\lfloor $1 \\right\\rfloor$0
endsnippet
```

Also, how can I return \\\\. In Javascript, one would simple write it as \\\\\\\\. This doesn't seem to work here.

**Comment by draivin** [comment]
Should be fixed on version 0.1.3!
