### ISSUE TITLE
Snippet expanding in-word when it shouldn't

### ISSUE THREAD

**Issue by medwatt** [draivin/hsnips#22]
According to your notes, "a snippet trigger will only match when the trigger is preceded by whitespace characters" unless the "i" flag is used.

The code below should expand for a1 as a_1 but shouldn't expand for item1 since the trigger is not preceded by whitespace characters.

```
snippet `[A-Za-z])(\d)` "auto subscript" A
``rv = m[1] + '_' + m[2]``
endsnip
```

It's quite easy to fix (as shown below), but I don't know this is correct behaviour ?
```
snippet `(?<= )([A-Za-z])(\d)` "auto subscript" A
``rv = m[1] + '_' + m[2]``
endsnip
```

**Comment by draivin** [comment]
Those matching flags are only used when not in regex mode currently. By default regex matches receive the line up until the caret as context, unless the `M` flag is specified, in which case it receives multiple lines.

I will thing about which behavior regex matches should have by default, if you have any thoughts please let me know.

**Comment by medwatt** [comment]
> Those matching flags are only used when not in regex mode currently. By default regex matches receive the line up until the caret as context, unless the `M` flag is specified, in which case it receives multiple lines.
> 
> I will think about which behavior regex matches should have by default, if you have any thoughts please let me know.

I think it makes sense to not include the flags for regex matches because that might interfere with the regex flags.

**Comment by draivin** [comment]
Added a footnote to the README so as to make the flags behavior more clear.
