### ISSUE TITLE
Hypersnips disables quicksuggestions

### ISSUE THREAD

**Issue by ZenghaoWang** [draivin/hsnips#23]
Hi, 

When the extension is disabled, vscode gives me pop-up suggestions as I type.
However, when hypersnips is enabled, this no longer occurs and only hyper snippets show up; I have to press ctrl+space to see the regular suggestions

**Comment by draivin** [comment]
Can you give me a reproducible example? What do you mean by quicksuggestions?

**Comment by ZenghaoWang** [comment]
For example, suppose I have a c source file open with the clangd language server (Although this works with any type of file) and hypersnips disabled:
![no_hsnips](https://user-images.githubusercontent.com/50110646/87807554-6199c000-c826-11ea-82f9-d71287b1eb29.gif)
As I type, vscode gives me intellisense suggestions.

Now on the same file with the only change being that hypersnips is enabled with a c.hsnips file:
![with_hsnips](https://user-images.githubusercontent.com/50110646/87807682-8db54100-c826-11ea-8a08-b1b0f4935b19.gif)
I have to manually press ctrl+space to get the same suggestions as before.

**Comment by draivin** [comment]
I made some changes in the latest version so as not to override other suggestion providers, so I'm closing this issue, if if you still have issues please let me know!
