### ISSUE TITLE
The replaced text will always trigger if the suffix is ​​the same as the prefix of a fragment

### ISSUE THREAD

**Issue by lancerXXXX** [draivin/hsnips#25]
The replaced text will always trigger if the suffix is ​​the same as the prefix of a fragment
![image](https://user-images.githubusercontent.com/42160297/87868782-3fda3d80-c9cc-11ea-9c7a-4468ac2a2904.png)
like this
it  will keep printing `AAAtest`,  because its suffix `test` is the same as the prefix `test`

**Comment by draivin** [comment]
Sorry about that, fixed in version 0.1.7.
