### ISSUE TITLE
when use multiple snippets, sometimes the $1 $2 leads to multiple cursors

### ISSUE THREAD

**Issue by clPointer** [draivin/hsnips#32]
the snippets i use:
![mark](http://anki20201112.xuexihaike.com/mpic/20201122/QjUJjPnHo9VG.png)
the problem i find:    (sorry for my bad typing skill. it may take a while for you to see it ;)
![mark](http://anki20201112.xuexihaike.com/mpic/20201122/UGoi0E6Yc57C.gif)
sorry for my bad typing skill.

**Comment by draivin** [comment]
As you seem to have found out, the issue is actually a vscode issue, https://github.com/microsoft/vscode/issues/87226, so it probably is out of scope of this project.
