### ISSUE TITLE
Expose More Variables

### ISSUE THREAD

**Issue by tigorlazuardi** [draivin/hsnips#33]
Hi. First of all, I love UltiSnips, when seeing your snippet engine, I'm excited VSCode potentially can have snippet engine as powerful as UltiSnips can be. Anyway, Can you add more variables to expose?

There's some things I want to access:
1. Current Buffer text (The whole document), as string or array of lines if possible (It may be slow, but it's friendly). Nice to have both (2 different variables).
2. The line index number where the snippet trigger.
3. The column index number where the snippet trigger.

Something nice to have:
1. Tab stop line number
2. Tab stop column line number

The purpose, if not obvious, is to have context around the snippet's trigger location.

Like for example in golang (basically ultisnips [example](https://github.com/SirVer/ultisnips/blob/8554371b57c8989cf73f73f288c456fb3f2a3a3a/doc/UltiSnips.txt#L1430)):
```go
file, err := os.Open("file.go")
```

by writing `if` in the next line, I get snippet that will expand to:
```go
if err != nil {
	$0
}
```

but if there's no `err :=` in the previous line, by writing `if` I get snippet that will expand to:
```go
if $1 {
  $0
}
```

I can easily do so by using line number where the snippet trigger as the index of Buffer Text document and use regex match on that index - 1 (previous line).

**Comment by khunspoonzi** [comment]
Column index would be really great.

There are a couple cases (related to comment formatting) where I would like to trim the line if it exceeds a certain length. As far as I can tell, I cannot currently do this without knowing the column index / indentation at which the snippet was triggered.

**Comment by draivin** [comment]
Closing this issue in favor of https://github.com/draivin/hsnips/issues/81, as currently there are a few proposed workarounds there.
