### ISSUE TITLE
there is something wrong with vim extension for vscode

### ISSUE THREAD

**Issue by lancerXXXX** [draivin/hsnips#36]
after they publish 1.17.x version, until now 1.18.5
after hypersnips triggers the snippets, vim will change to Visual mode, which should normally keep insert mode

![image](https://user-images.githubusercontent.com/42160297/105146455-fb765880-5b3a-11eb-9a81-785a330e8137.png)

![image](https://user-images.githubusercontent.com/42160297/105146456-fb765880-5b3a-11eb-8413-d3588fcf3a48.png)
In fact, the previous version 17 had this problem with vscode's own block engine, too , but it was fixed in version 18

**Comment by lancerXXXX** [comment]
Works fine with 1.16.0

**Comment by lancerXXXX** [comment]
the vim extension , I means this one
![Uploading image.png…]()

**Comment by lancerXXXX** [comment]
the vim extension , I mean this one
![image](https://user-images.githubusercontent.com/42160297/105147454-2b722b80-5b3c-11eb-8c0f-b84a36e70ef8.png)

**Comment by ZenghaoWang** [comment]
I have this problem as well, and it makes using hypersnips with the vim extension basically unusable.
