### ISSUE TITLE
Error using a file other than all.hsnips 

### ISSUE THREAD

**Issue by fer334** [draivin/hsnips#37]
If I use this file all.hsnips, the snippet works without problems but when adding another file it stops working and in the development tools an error appears 
![image](https://user-images.githubusercontent.com/48743058/106472506-803d6c80-6481-11eb-9b3b-61d0553f2849.png)

**Comment by draivin** [comment]
Is the issue still present? If so please reopen the issue, I can't seem to reproduce it.
