### ISSUE TITLE
Snippet in Snippet

### ISSUE THREAD

**Issue by franto666** [draivin/hsnips#38]
Hello, there is a problem that I have encountered that is starting to give many problems.
When I try to expand one snippet into another, I can't, unless the latter is an automatic snippet (iA, wA, bA ...).
When I try to activate a snippet (which requires the tabulator) inside another snippet, the latter will not be able to operate.
Please solve the problem.

Thanks in advance.

https://user-images.githubusercontent.com/77899243/109388581-46d51100-7908-11eb-986b-23f0796f3254.mp4

**Comment by Francesco-2003** [comment]
I have the same problem

**Comment by Antonella112** [comment]
So am I

**Comment by kaizokugarizoro** [comment]
Same! There's this grey bar that appears every time I open a snippet inside another snippet. The dynamic snippets do work sometimes though, but not the static ones.

**Comment by draivin** [comment]
Could one of you please check if it works on the previous version of hsnips?

**Comment by kaizokugarizoro** [comment]
> Could one of you please check if it works on the previous version of hsnips?
> 
> Also, I've just tested it and can't seem to reproduce the issue, could you send a pair of snippets that consistently won't expand?

Hi draivin. So any of the snippets that are not set to auto-expand 'A', and need Tab to be pressed at the end, aren't working for me personally. They do work once I press ESC and exit that grey highlight mode, but pressing ESC each time I open a snippet is a big issue for me. 

As an example, I'm using this snippet for .tex files

snippet subtemplate "subfile template" b   
%! TEX TS-program = xelatex
\documentclass[../${1:main.tex}]{subfiles}
\begin{document}
$0
\end{document}
endsnippet 


And the grey highlight issue I mentioned is as shown in the picture attached.
![image](https://user-images.githubusercontent.com/69515542/110433935-2743a280-80d7-11eb-9f07-07d89b82b530.png)

**Comment by kaizokugarizoro** [comment]
> Could one of you please check if it works on the previous version of hsnips?
> 
> Also, I've just tested it and can't seem to reproduce the issue, could you send a pair of snippets that consistently won't expand?

Also, is there any way to roll back to a previous version? Because I just installed it from VSCode Extensions Market.

**Comment by franto666** [comment]
Thanks to everyone for the answers, I will send a longer video today to show the problem in more detail.

**Comment by Francesco-2003** [comment]
hi, I also tried installing previous versions (I tried them all) but the problem remains the same, non-automatic snippets in automatic snippets do not work

**Comment by draivin** [comment]
Hey guys, this seems to be a vscode option, can you try setting the following option?
```json
"editor.suggest.snippetsPreventQuickSuggestions": false
```

**Comment by Francesco-2003** [comment]
hi, i did what you said and now the snippets that are not automatic are displayed as I type in the automatic ones, but when I press tab, VSCode does not understand that I want to expand the non-automatic snippet, it takes me to the other position of the automatic snippet.

**Comment by franto666** [comment]
thanks a lot guys, but I can't understand why you have to click Enter, and not Tab to activate everything
<img width="749" alt="Schermata 2021-03-10 alle 19 59 32" src="https://user-images.githubusercontent.com/77899243/110682365-23994400-81db-11eb-9dde-48e3a6cb63f7.png">
PS: this is what I had added to Ultisnips to make it work as I asked, if you can help me configure it in the same way please !!

**Comment by kaizokugarizoro** [comment]
> thanks a lot guys, but I can't understand why you have to click Enter, and not Tab to activate everything
> <img alt="Schermata 2021-03-10 alle 19 59 32" width="749" src="https://user-images.githubusercontent.com/77899243/110682365-23994400-81db-11eb-9dde-48e3a6cb63f7.png">
> PS: this is what I had added to Ultisnips to make it work as I asked, if you can help me configure it in the same way please !!

YES. I'm also looking for precisely the same thing!

**Comment by gruvw** [comment]
I have the same issue, trying to expand nested snippets is going to the next placeholder instead.

**Comment by draivin** [comment]
Hey guys, sorry, it seems it took @gruvw's bug report for me to understand what you meant. You can see a solution to this in a reply I posted [here](https://github.com/draivin/hsnips/issues/42#issuecomment-841778767), I'll close this issue as the solution is in the other one, if there are any further questions please post there!
