### ISSUE TITLE
Expanding snippet inside another snippet interrupts code interpolation

### ISSUE THREAD

**Issue by Einlar** [draivin/hsnips#4]
I have two snippets: the first one inserts a math block ($$), followed by a space if the first character in the last placeholder is not in some set of characters.

    snippet mk "inline math" A
    \$$1\$``if (t[1] && ",-.? ".indexOf(t[1][0]) >= 0) { rv = '' } else { rv = ' ' }``$2
    endsnippet

The second snippet formats every string of an alphabetical character followed by a number in the following way: a2 => a_{2}

    snippet `([a-zA-Z])([0-9]+)` "underset" A
    ``rv = m[1] + '_{' + m[2] + '} '``
    endsnippet

Both snippets work fine on their own. However, if I use one "inside" the other, for example by typing `mka2<Tab>?` the return value of the "outer" code interpolation (i.e. the "inline math" one) gets interrupted. In this case I expect to get "$a_{2}$?" (without the space), but I get "$a_{2}$ ?" (with the space).

This is more easy to see by typing "a2" inside the "box" snippet reported in the examples:

    snippet box "Box" A
    ``rv = '┌' + '─'.repeat(t[0].length + 2) + '┐'``
    │ $1 │
    ``rv = '└' + '─'.repeat(t[0].length + 2) + '┘'``
    endsnippet

The problem persists even if the "inner" snippet is not dynamic (it is without the "A" in the definition, requiring <Tab> to expand), or it doesn't contain any code interpolation. Note that using a usual VS code snippet inside an hsnips snippet works as expected, without any problem.

**Comment by draivin** [comment]
Fixed on version 0.0.15!
