### ISSUE TITLE
请问如何在hsnips配置文件中注释掉暂时不用的代码

### ISSUE THREAD

**Issue by aqlkzf** [draivin/hsnips#44]
请问如何在hsnips配置文件中注释掉暂时不用的代码

**Comment by yfzhao20** [comment]
我觉着在`snippet`和`endsnippet`前面加上`\\`就能让插件不认识这一段，至少我这样用没出什么bug

**Comment by draivin** [comment]
Hello, unfortunately I can't read chinese, but it seems you are asking how to add comment to hsnips files. Currently the parser simply ignore everything that is outside a `snippet` or `global` block, but following the original ultisnips behavior, I would use `#` as the first character in a line to comment it, this is the behavior that will be supported going forwards.

**Comment by draivin** [comment]
Just added syntax highlighting for `#` comments, closing this issue now.
