### ISSUE TITLE
Bug: trigger not working if ending with some characters

### ISSUE THREAD

**Issue by gruvw** [draivin/hsnips#46]
I found a weird behavior in the new version:

For some reasons, this is not working anymore:
```
snippet a1 "Issue 1" A
Not working
endsnippet

snippet `a2` "Issue 2" A
Not working
endsnippet

snippet `a\/` "Issue 3" A
Not working
endsnippet
```

If the trigger is not ending with a `[A-Za-z\#\>]` character, it will not work. 

This only occurs in math center mode, with line breaks: 
```
\[
    a1
\]
$$
a1
$$
```

**Comment by draivin** [comment]
Should be fixed on latest version of `hscopes`. 🙂
