### ISSUE TITLE
Can't use regex with normal completion

### ISSUE THREAD

**Issue by Ubuntu-prog** [draivin/hsnips#56]
I recognised that regex expressions don't seem to work with normal tab completion. Whenever I use regex in a snippet without adding the `A` flag, which I don't want because I need tab completion, it doesn't work.

**Comment by SASY-2333** [comment]
You may not open the ```quickSuggestions```.
I also meet this issue in the markdown file, but I have solved it as followings:
1. Search the ```suggestion markdown``` in the settings, and edit it in the ```settings.json```.
![temp1](https://user-images.githubusercontent.com/56601845/133025774-243f1f6a-d09d-453d-b19c-1a6f36bc71d2.jpg)
2. Set the ```editor.quickSuggestions``` to be ```true```, then it works.
![temp2](https://user-images.githubusercontent.com/56601845/133025793-78b0c653-f9f7-4fa3-ada4-e5bb93ee7b66.jpg)

**Comment by draivin** [comment]
Fixed in https://github.com/draivin/hsnips/pull/76.
