### ISSUE TITLE
Does HyperSnips support selected variable?

### ISSUE THREAD

**Issue by pilgrimlyieu** [draivin/hsnips#66]
![](https://castel.dev/0da01b9566dc437fabf0c563ed14941f/visualfrac.gif)

[original source](https://castel.dev/post/lecture-notes-1/)

>The code makes use of the ${VISUAL} vari­able that rep­re­sents your se­lec­tion.

```snippets
snippet / "Fraction" iA
\\frac{${VISUAL}}{$1}$0
endsnippet
```

Can it be acheived?

Additionally, UltiSnips support python. And can acheieve a cool function like support Sympy and Mathematica calculate. It'll be better if it can be realized.

By the way, extremely thanks for your efforts to create such a wonderful plugin!!!

**Comment by gruvw** [comment]
Might be duplicate of #16 and #20

**Comment by pilgrimlyieu** [comment]
> Might be duplicate of #16 and #20

Thanks! But it seems not to be solved.
