### ISSUE TITLE
Feature request: priority of snippets

### ISSUE THREAD

**Issue by Einlar** [draivin/hsnips#7]
It would be useful to assign a _priority_ value to snippets, determining their order of evaluation, like in UltiSnips:

    priority 10
    snippet test "Just a test"
    Hello!
    endsnippet

So that snippets with higher priority are evaluated before others, and snippets with the same priority are evaluated in the order they appear in code. This could be especially useful to control "snippet cascades", where the output of a higher priority snippet triggers another lower priority snippet.

**Comment by draivin** [comment]
Added on version `0.0.16`!
