### ISSUE TITLE
Can't use snippets in placeholders which have more than one in a time.

### ISSUE THREAD

**Issue by pilgrimlyieu** [draivin/hsnips#72]
![2](https://user-images.githubusercontent.com/80107081/131285992-16ef4d1c-9319-4ae5-8229-9293a59ff130.gif)

Here are testing snippets.

```snippets
snippet test1 "test" Ai
($1,$1)$0
endsnippet

snippet test2 "test" Ai
($1,$2)$0
endsnippet

snippet example "example" Ai
This is an example.
endsnippet
```

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Your video shows the expected behavior. Don't quite understand your confusion. Could you add more details of your problem?

**Comment by yfzhao20** [comment]
He means, "example" in line 2 code should be expanded into "This is an example". I have tested and confirmed that.

**Comment by pilgrimlyieu** [comment]
> He means, "example" in line 2 code should be expanded into "This is an example". I have tested and confirmed that.

That's it!

**Comment by pilgrimlyieu** [comment]
Close because this issue is stale.
