### ISSUE TITLE
Allow returning `rv` through asynchronous functions

### ISSUE THREAD

**Issue by noisnemid** [draivin/hsnips#74]
if there are some functions that async methods involved, then how to give rv a value?
```
global
function foo()
{
    let bar = 'some_string';
    let exec = require('child_process').exec
    let cmd = [
        'some_shell_command',
        'some_args',
        bar
    ].join(' ')

    call2(cmd, (error, stdout, stderr) =>
    {
        //how to return this stdout value to rv?
    });
}

endglobal
```
It's possible to use child_process.execSync, but is it possible to use some async functions, such as Promise or else?

If the foo changed to async fashion, the rv will get a Promise object, not the values inside the Promise objects or its thenable porcedrues.

**Comment by draivin** [comment]
Sorry for the delay in getting to this, currently it is not possible, and it is not even in the plans to allow something like this, the code overhead to support async functions would be huge, and would probably require a rewrite of the text replacement logic.
