### ISSUE TITLE
How to change TabStop contents dynamicly

### ISSUE THREAD

**Issue by Weiged** [draivin/hsnips#75]
I want to replace all "." in $1 to "/"

**Comment by pilgrimlyieu** [comment]
> I want to replace all "." in $1 to "/"

Maybe you can try this code.

```javascript
t[0] = t[0].replace(/\./, "/")
```

**Comment by Weiged** [comment]
> > I want to replace all "." in $1 to "/"
> 
> Maybe you can try this code.
> 
> ```js
> t[0] = t[0].replace(/\./, "/")
> ```

That doesn't help.

**Comment by pilgrimlyieu** [comment]
> > > I want to replace all "." in $1 to "/"
> > 
> > 
> > Maybe you can try this code.
> > ```js
> > t[0] = t[0].replace(/\./, "/")
> > ```
> 
> That doesn't help.

Sorry, I ignored a problem. The solution is

```javascript
t[0] = t[0].replace(/\./g, "/")
```

**Comment by draivin** [comment]
These kinds of questions should probably be as discussions, I guess it is solved now anyways, so I'm closing!
