### ISSUE TITLE
How to recognize some specific expression after the snippet?

### ISSUE THREAD

**Issue by yfzhao20** [draivin/hsnips#77]
Hi! I'm thinking about an interesting idea, i.e. recognize some specific words after main snippets.

 For example, I want to expand "hello" to "hellotest" only when there is an "a" after my cursor, i.e. `bcca`→input→`bcchelloa`→expand→`bcchellotesta`

However regex can  only be used to recognize the words before main snippets, for exp, this snippet can only recognize "a" before "hello" , and then turn "hello" into "hellotest".
```
snippet `(a)hello` "hello" iA
``rv=m[1]``hellotest
endsnippet
``` 

Maybe I can make it with  `JavaScript` ? Or if I need `Context`?
Sorry for my not-so-fluent English...

Thanks!

**Comment by pilgrimlyieu** [comment]
I've tried to make it. And that's my achievement.

```javascript
snippet `(hello)(\w+)` "hello test" Ai
``
let string = m[1];
let title = m[2];
if (title == "a"){
    rv = m[1] + "test"
}
else {
    rv = m[0]
}
``
endsnippet
```

However, I don't agree with this solution.

**Comment by pilgrimlyieu** [comment]
In addition, I make a function to make it more convenient.

```javascript
global
// string means the main string
// title means the letter or words after the string
// trigger means the trigger sign
// replace means the replacement
// option means if you want to replace the whole string with replacement
function Test(string, title, trigger, replace, option){
    if (title == trigger){
        if (option == 1){
            result = replace
        }
        else {
            result = string += replace
        }
    }
    else {
        result = string + title
    }
    return result
}
endglobal

snippet `(hello)(\w)` "hello test" Ai
``
rv = Test(m[1], m[2], "a", "test", 0)
``
endsnippet
```

**Comment by pilgrimlyieu** [comment]
咦，有幸拜读过您的知乎文章，原来都是国人，国庆快乐！
英语太差了，写的好难受。

**Comment by yfzhao20** [comment]
hey！我的英文也一般般😂，但是作者Draivin似乎不是很熟悉中文😂

之前的提问是说，如果光标后面**本来存在**一个"a"，那么在此光标处**只**输入一个"hello"，他将自动展开为"hellotest"，即（用`|`代替光标位置）：`mar|a`→`marhello|a`→`marhellotest|a`

但上述代码的结果是，本来存在的`a`并不起作用，只有输入"helloa"，才能变为"hellotest"。

这个issue的本意是，仅使用hsnips实现一个括号自动补全的片段。即，输入左括号 `(`，在 `[a-zA-Z]` 前面不会补全右括号，而其他情况则自动补全右括号 `)`。道理都是相同的

仍非常感谢！

另，祝国庆快乐😃

---

English ver.

This solution maybe can not give an expected result. 🤔

**Comment by pilgrimlyieu** [comment]
我也尝试过制作括号补全，但最后放弃了。不过我记得VSnips似乎可以满足，我尝试它用过VBox，在输入完成后再进入VBox仍然能使VBox扩张，我不清楚原理，但我认为你可以尝试一下。
---
VSnips maybe can solve it.

**Comment by draivin** [comment]
I don't think this is exactly in the scope of this extension, so I'm closing this issue in favor of #81, as currently there are a few proposed workarounds there (that you suggested 😄 ).
