### ISSUE TITLE
Scope behavoir becomes random after a while 

### ISSUE THREAD

**Issue by hainingpan** [draivin/hsnips#79]
The snippet which is intended in the context of math can be triggered even when it is in the text mode after using it for a while.

The scope is defined as
```
global
function math(context) {
    return context.scopes.some(s => s.startsWith("meta.math"));
}
endglobal
```

Here is an example of such unexpected behavior (note that the scope is always `text.tex.latex`, yet the snippet is triggered automatically) 
![vscode_hypersnips](https://user-images.githubusercontent.com/22186947/135150435-8f9e8f2c-f980-477a-ad73-220ccf05cb19.gif)

The snippet triggered here is (though it does not matter, every snippet can be triggered)
```
context math(context)
snippet `([\s])([A-Za-z])([\w]) ` "auto subscript" A
``rv=' '+m[2]+'_{'+m[3]+'} '``
endsnippet
```

It is difficult to reproduce this because once I restart vscode, everything becomes normal. But if I continue to use it for a while, this random behavior starts again.

Any comment for this or can I do something to show more debug info when this happens?

**Comment by yfzhao20** [comment]
I don't think so @A6669 . Maybe hscopes recognize the environment by getting `textmate scopes` . I met the same problem recently and I'm looking forward to the solution.

**Comment by A6669** [comment]
> I don't think so @A6669 . Maybe hscopes recognize the environment by getting `textmate scopes` . I met the same problem recently and I'm looking forward to the solution.

you use \(\) or $?

**Comment by A6669** [comment]
> Mostly `$$`. But you see , that problem emerges **randomly**. In most cases, it works normally. And after I reload VSCode, the problem disappears in the same position.

try https://github.com/OrangeX4/hsnips

**Comment by AnthonyOKC** [comment]
I have the same exact behavior as described by @yfzhao20. Both in that, the bug is seemingly random (the same action, the same position will only **sometimes** work) and that the bug is only fixed by restarting vscode. The only difference is I use \(\) instead of $$ but clearly, this does not make a difference. I have had no other issues with the extension thus far so I hope this can be fixed as it is one of my favorite extensions.

**Comment by A6669** [comment]
> I have the same exact behavior as described by @yfzhao20. Both in that, the bug is seemingly random (the same action, the same position will only **sometimes** work) and that the bug is only fixed by restarting vscode. The only difference is I use \(\) instead of $$ but clearly, this does not make a difference. I have had no other issues with the extension thus far so I hope this can be fixed as it is one of my favorite extensions.

Maybe it is a bug in vscode.

**Comment by sleepymalc** [comment]
@A6669 Using `\(\)` doesn't work too. I used `\(\)` for a long time, and I still ran into this problem. Everything is fine after restarting VSCode though.

**Comment by DedZago** [comment]
Is there any progress on this issue? I keep encountering it even with other contexts such as fenced code blocks in quarto markdown, i.e.
```
global
function r_code(context) {
    return context.scopes.some(s => s.startsWith("meta.embedded.block.r"));
}
endglobal
```
Sometimes snippet that are defined only in fenced blocks start expanding even in regular text, hence it seems to me that it is more general than simply math environments being broken..

This is really annoying, given that snippet expansion is a big part of my workflow.. If there are no workaround to this bug, I might consider returning to neovim and Ultisnips.

**Comment by draivin** [comment]
Should be greatly improved as of latest patch, if there are new issues please open a new issue or reopen this one.

**Comment by DiegoRodriguezT** [comment]
I keep having the same problem, any update? :(

**Comment by jsiph2** [comment]
Hi, I also have been having this issue. Restarting VSCode works to fix it, but only temporarily.

**Comment by A6669** [comment]
> Hi, I also have been having this issue. Restarting VSCode works to fix it, but only temporarily.

uninstall hsnip, and try this https://marketplace.visualstudio.com/items?itemName=Oskar-Idland.HyperSnipsV2
