### ISSUE TITLE
extension stopped working on new computer

### ISSUE THREAD

**Issue by jonas-frey** [draivin/hsnips#80]
I got a new laptop and copied hsnips files over while setting up vscode.

But now hsnips doesn't seem to work anymore with *tex files. On my old computer I had the *tex snippets in a file hsnips.latex and it works, but I tried both hsnips.tex and hsnips.latex on the new one and it still doesn't work. I also have an hsnips.hsnips and that works on the new computer. Both computers run ubuntu 21.04

Anyway, when I hover over the extension in the sidebar, the popup says ` This extension has reported 808 uncaught errors`, and when I click on the link I get a long list of `Cannot read property 'text' of undefined` and `Cannot read property 'scopes' of null`.

I'm using the latex workshop extension with latex, but I tried to deactivate all extensions and that doesn't help either. 

Any help would be highly appreciated!

**Comment by changxvv** [comment]
I got the same problem when I tried to use it on wsl2
![image](https://user-images.githubusercontent.com/40617368/135840558-9dc38db1-1de6-4c2f-a097-7cdc899620a7.png)

**Comment by jonas-frey** [comment]
Update: it's working now, I think the issues were partially related to another extension misbehaving. Unfortunately I can't give a precise diagnosis.
