### ISSUE TITLE
Second tab placeholder fails

### ISSUE THREAD

**Issue by hinell** [draivin/hsnips#83]
Tabs that follow a JS block inside a snippet fail the whole thing to compile. Try to complete the `failure` as usual - it won't.

```lua
snippet failure "" w
$1 
`` rv = '$1 length is ' + (t[0] || '').length + '$2 length is' + (t[1] || '').length)``
$2
endsnippet

```

### Versioning
- v0.2.2

**Comment by draivin** [comment]
The compilation issue here is an extra parenthesis at the end of the javascript code block. There was another error related to dollar sign escaping, but that is fixed as of the latest release.
