### ISSUE TITLE
Feature request: open snippets file inside VSCode

### ISSUE THREAD

**Issue by jacopok** [draivin/hsnips#9]
Right now there is only a command to open the snippets directory, however it would be useful for quick fixes to snippets while working if there was a way to open the `.hsnips` file directly in VSCode from the command palette, as is the case with regular VSCode snippets files with the command `Preferences: configure user snippets`.

**Comment by draivin** [comment]
Thanks for the feedback, I added a basic implementation of the command in version `0.0.16`, it's called `HyperSnips: Open Snippet File`.

I'll come back to it once I have more time and add the option to create snippet files from the selection menu, as in the default one.
