### ISSUE TITLE
HyperSnips extension doesn't work at all?

### ISSUE THREAD

**Issue by Chiron19** [draivin/hsnips#93]
After installing this extension, it doesn't trigger anything, why?  I have set `all.hsnips`, `latex.hsnips`, `tex.snips` in the correct way.

And it appears error like that and doesn't work at all.

The snips directory is ` C:\Users\surface\AppData\Roaming\Code\User\hsnips`, but it cannot reload snippets.
![000](https://user-images.githubusercontent.com/59187993/142768098-ddc28020-1a5d-4939-9401-8ea54d86852a.jpg)
![111](https://user-images.githubusercontent.com/59187993/142768099-9fd660cb-3494-43ec-ae44-c77bbb209c3f.jpg)

Could you please offer some help and figure out why and how to solve? Thanks a lot!

**Comment by yfzhao20** [comment]
Maybe you can delete `%userprofile%/.vscode/extensions/draivin.hsnips-0.2.2` and then reinstall the extension? Last time I solve this problem in this way.

**Comment by Chiron19** [comment]
> Maybe you can delete `%userprofile%/.vscode/extensions/draivin.hsnips-0.2.2` and then reinstall the extension? Last time I solve this problem in this way.

The problem has been solved by your instruction. I clear the extension file and snippets documents and then reinstall the extension and rewrite the snippets. After doing so, it was fixed and shows no error.

Thanks a lot. 🙌
