### ISSUE TITLE
Regex trigger doesn't show in the completion list when in Jupyter Notebook

### ISSUE THREAD

**Issue by sffred** [draivin/hsnips#95]
As is mentioned in #76 and #56 , times are when the regex trigger doesn't works. And although in other situations this issue has been fixed, when editing in a .ipynb file using the  buit-in Jupyter notebook it still exists. You have to use a A flag to get the regex to work. The completion list just shows 'no suggestions'

**Comment by yfzhao20** [comment]
Can you provide the screenshot? maybe I can find the solution.

**Comment by sffred** [comment]
> Can you provide the screenshot? maybe I can find the solution.

![Screenshot from 2021-12-01 21-50-31](https://user-images.githubusercontent.com/62537226/144246819-1385453f-714c-407f-b7e7-a16bf1a31e49.png)

![Screenshot from 2021-12-01 21-55-37](https://user-images.githubusercontent.com/62537226/144246961-1e57412b-67cd-4e5a-b6c7-903cff5d3f35.png)

**Comment by yfzhao20** [comment]
I have tested that and confirmed the bug. And I'm sorry to say I don't know why...

But built-in snippets (from "user snippets" and `markdown.json` can show.

**Comment by draivin** [comment]
Fixed in latest patch, thanks for the report.
