### ISSUE TITLE
Command 'HyperSnips: Reload Snippets' resulted in an error (Invalid or unexpected token)

### ISSUE THREAD

**Issue by universemaster** [draivin/hsnips#96]
Hypersnips stops working and reloading snippets gives

>Command 'HyperSnips: Reload Snippets' resulted in an error (Invalid or unexpected token)

On version "07/12/2021, 10:12:41", 0.2.4

It's fine on 0.2.3.

**Comment by draivin** [comment]
I can't reproduce this issue, can you send me a minimum reproducible example? Or otherwise send me the relevant `hsnips` files.

**Comment by universemaster** [comment]
Thanks, here is the [gist](https://gist.github.com/universemaster/2d4dbcbd0366a12c47d0b6bbe1d60562) of my `markdown.hsnips` .

**Comment by draivin** [comment]
The issue is with your `column vector` snippet, we had a change in the parser, so currently there is no way to define two code blocks without any characters in between. You can change your snippet so that the first code block `rv` is in the second code block.
