### ISSUE TITLE
May I use @#$% as a trigger without A (Auto expend)?

### ISSUE THREAD

**Issue by qninth** [draivin/hsnips#98]
```
snippet %% "big star" A
$\color{red}\bigstar$ 
endsnippet
```

Here is a simple snippet. When I delete A, it cannot work anymore.
Is there any way to use this without auto expend?

**Comment by qninth** [comment]
I try to add \t after %% but it didn't work.
I've added space and semicolon as triggers for now.
If you have a way to use the Tab as a trigger, please let me know.

**Comment by draivin** [comment]
Fixed in version 0.2.7, thanks for the report!
