### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined in hsnips-0.2.4

### ISSUE THREAD

**Issue by rioj7** [draivin/hsnips#99]
I get a lot of the following errors in the Developer Tools of VSC

```
TypeError: Cannot read property 'text' of undefined
	at /XXXX/.vscode/extensions/draivin.hsnips-0.2.4/out/extension.js:114:24
```

**Comment by draivin** [comment]
Hello, could you tell me how to reproduce this issue? Perhaps share your `all.hsnips` and relevant language hsnips file?

Also, does this happens in a specific language, or do you always get this error, regardless of the language of the file you are editing?
